### ISSUE TITLE
Example of working code

### ISSUE THREAD

**Issue by delchiaro** [ValentinnDimitroff/ra-compact-ui#1]
Hi,
I really like the work you made, but it's difficult to understand how to use this package.
If you could provide an example of code I would really appreciate.

Thanks

**Comment by ValentinnDimitroff** [comment]
Hey there and thank you! I have just published the package yesterday and it is a bit work in progress. But I will add examples tomorrow regarding the present components so that you can start using them. And any future feedback is more than welcome!

**Comment by ValentinnDimitroff** [comment]
There you go, mate ;) Hope you find it helpful

**Comment by delchiaro** [comment]
Thank you very much!!!
